const playlists = {
  happy: {
    pop: [
      "37i9dQZF1DWVlYsZJXqdym",
      "37i9dQZF1DX1H4LbvY4OJi",
      "37i9dQZF1DX1WSnLRtI26o",
      "5jUzGL1fs9050Iu5jQIWgD",
    ],
    hiphop: [
      "1ZNuF0eUagiOhDFvhiKGJ7",
      "77m7vYBY8SZW2c1hlIT4S8",
      "2l3zXpmezQBYf93rN2kyKI",
      "5H7f1oXhWEDnpytBArldMM",
    ],
    country: [
      "37i9dQZF1EIf6meFuWnpYx",
      "78Mik4SeJkhoPnT6NagsVc",
      "7J4e49SxlE8KhqqXHQIAgK",
      "0vmOmFbo4upEmeeR9GebQo",
    ],
    rock: [
      "2BumzROvyilNPyczjghkba",
      "5RANr63hkgcUwUDsiUry4r",
      "67igeRlKxEXoPI266QNEGd",
      "2esHfruMW8rAZI2DxQCNcj",
    ],
    indie: [
      "37i9dQZF1DX2sUQwD7tbmL",
      "6temCsuHDj18AKkVRVyKaK",
      "7ePYwKhmDgPcqkrrYz87ki",
      "7fdcXXKn83lI0uestEdwvJ",
      "56zDJ1h8dv7Dbi3uOsMIR6",
    ],
  },
  sleepy: {
    pop: [],
    hiphop: [],
    country: [],
    rock: [],
    indie: [],
  },
  pumped: {
    pop: [],
    hiphop: [],
    country: [],
    rock: [],
    indie: [],
  },
  angry: {
    pop: [],
    hiphop: [],
    country: [],
    rock: [],
    indie: [],
  },
  heartbroken: {
    pop: [],
    hiphop: [],
    country: [],
    rock: [],
    indie: [],
  },
  chill: {
    pop: [],
    hiphop: [],
    country: [],
    rock: [],
    indie: [],
  },
  focused: {
    pop: [],
    hiphop: [],
    country: [],
    rock: [],
    indie: [],
  },
  fire: {
    pop: [],
    hiphop: [],
    country: [],
    rock: [],
    indie: [],
  },
  meh: {
    pop: [],
    hiphop: [],
    country: [],
    rock: [],
    indie: [],
  },
  loved: {
    pop: [],
    hiphop: [],
    country: [],
    rock: [],
    indie: [],
  },
  sad: {
    pop: [],
    hiphop: [],
    country: [],
    rock: [],
    indie: [],
  },
  party: {
    pop: [],
    hiphop: [],
    country: [],
    rock: [],
    indie: [],
  },
};

export { playlists };

//   [
//     "37i9dQZF1DXdPec7aLTmlC",
//     "37i9dQZF1EVJSvZp5AOML2",
//     "37i9dQZF1DX0UrRvztWcAU",
//     "37i9dQZF1DWZKuerrwoAGz",
//     "37i9dQZF1DX1H4LbvY4OJi",
//     "37i9dQZF1DWYBO1MoTDhZI",
//     "37i9dQZF1DX3rxVfibe1L0",
//   ],
//   sad: [
//     "37i9dQZF1DWZUAeYvs88zc",
//     "37i9dQZF1DX7qK8ma5wgG1",
//     "37i9dQZF1DWVV27DiNWxkR",
//     "37i9dQZF1DWZFicI79sEj9",
//     "37i9dQZF1DWSqBruwoIXkA",
//     "37i9dQZF1DXa39zZwdBPSN",
//   ],
//   party: [
//     "37i9dQZF1DXa2PvUpywmrr",
//     "37i9dQZF1DWXti3N4Wp5xy",
//     "37i9dQZF1DX7e8TjkFNKWH",
//     "37i9dQZF1DWWylYLMvjuRG",
//     "37i9dQZF1DXdo6A3mWpdWx",
//     "37i9dQZF1DXaXB8fQg7xif",
//   ],
